set rtp=$CBASH_DIR/vim,/usr/share/vim,/usr/share/vim/*
set nocompatible              " be iMproved, required
filetype on                   " required for compatibility with Mac OS X, See issue Vundle#167
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$CBASH_DIR/vim/bundle/Vundle.vim
" alternatively, pass a path where Vundle should install plugins
call vundle#begin("$CBASH_DIR/vim/plugins")

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Other plugins
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tomtom/tcomment_vim'

call vundle#end()     " required
filetype indent on    " required

let g:netrw_home=$CBASH_DIR.'/vim'

set viminfo+=n$CBASH_DIR/vim/viminfo

syntax on

set ruler
set autowrite
set nobackup
set nowritebackup
set noswapfile
set number
set cursorline
set showcmd
set wildmenu
set mouse=a
set hlsearch
set incsearch
set relativenumber

" panes
set splitbelow
set splitright

" indentiation config
set tabstop=2 softtabstop=0 shiftwidth=2 smarttab

" theme
colo jitterbug


" somewhat better trackpad scrolling
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
