# load aliases
source $CBASH_DIR/aliases/aliases.bash
source $CBASH_DIR/aliases/git.aliases.bash

# add custom bin folder to path
export PATH="$PATH:$CBASH_DIR/bin"

export INPUTRC=$CBASH_DIR/profiles/inputrc

# history config
export HISTSIZE=
export HISTFILESIZE=
export HISTCONTROL=ignoreboth:erasedups

# vim config
export VIMINIT="source $CBASH_DIR/vim/vimrc"

# add some color to terminal
export CLICOLOR=1
export LSCOLORS=Bxfxcxdxbxegbhabagacad

# import custom git prompt
source $CBASH_DIR/git/git-bash/custom-prompt.sh

export PS1="\[\033[33;1m\]\W\[\033[m\] "
PS1+='\[\e[0;36m\]$(_git_branch)\[\e[0;36m\]$(_git_dirty)\[\e[0m\]'
