# load aliases
source $CBASH_DIR/aliases/aliases.bash
source $CBASH_DIR/aliases/git.aliases.bash

# add custom bin folder to path
export PATH="$PATH:$CBASH_DIR/bin"

export INPUTRC=$CBASH_DIR/profiles/inputrc

# history config
export HISTSIZE=
export HISTFILESIZE=
export HISTCONTROL=ignoreboth:erasedups

# vim config
export VIMINIT="source $CBASH_DIR/vim/vimrc"

# add some color to terminal
export CLICOLOR=1
export LSCOLORS=Bxfxcxdxbxegbhabagacad

# git prompt, helpful for quicky repo glance
source $CBASH_DIR/git/git-bash/git-prompt.sh

# PS1
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1="\[\033[33;1m\]\W\[\033[m\] "
export PS1=$PS1'$(__git_ps1 "\[\e[0;32m\](%s) \[\e[0m\]")'

if [ -f $CBASH_DIR/git/git-bash/git-completion.bash ]; then
	source $CBASH_DIR/git/git-bash/git-completion.bash
fi

